# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 1521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.profile)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridWidget_2 = QtWidgets.QWidget(self.profile)
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.basic_russian_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_russian_max_2.setText("")
        self.basic_russian_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_russian_max_2.setObjectName("basic_russian_max_2")
        self.gridLayout_10.addWidget(self.basic_russian_max_2, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_18.setStyleSheet("font-size: 15px; font-weight: 600;border-bottom:1px solid black;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_19.setStyleSheet("font-size: 15px; font-weight: 600;border-bottom:1px solid black;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 0, 1, 1)
        self.long_russian_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_russian_counter_2.setText("")
        self.long_russian_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_russian_counter_2.setObjectName("long_russian_counter_2")
        self.gridLayout_10.addWidget(self.long_russian_counter_2, 3, 3, 1, 1)
        self.hard_russian_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.hard_russian_avg_2.setText("")
        self.hard_russian_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hard_russian_avg_2.setObjectName("hard_russian_avg_2")
        self.gridLayout_10.addWidget(self.hard_russian_avg_2, 5, 2, 1, 1)
        self.hard_russian_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.hard_russian_max_2.setText("")
        self.hard_russian_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hard_russian_max_2.setObjectName("hard_russian_max_2")
        self.gridLayout_10.addWidget(self.hard_russian_max_2, 5, 1, 1, 1)
        self.basic_russia_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_russia_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_russia_name_2.setObjectName("basic_russia_name_2")
        self.gridLayout_10.addWidget(self.basic_russia_name_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_2.setStyleSheet("font-size: 15px; font-weight: 600;border-bottom:1px solid black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 1, 1, 1)
        self.long_russian_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_russian_max_2.setText("")
        self.long_russian_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_russian_max_2.setObjectName("long_russian_max_2")
        self.gridLayout_10.addWidget(self.long_russian_max_2, 3, 1, 1, 1)
        self.basic_russian_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_russian_avg_2.setText("")
        self.basic_russian_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_russian_avg_2.setObjectName("basic_russian_avg_2")
        self.gridLayout_10.addWidget(self.basic_russian_avg_2, 1, 2, 1, 1)
        self.long_russian_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_russian_avg_2.setText("")
        self.long_russian_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_russian_avg_2.setObjectName("long_russian_avg_2")
        self.gridLayout_10.addWidget(self.long_russian_avg_2, 3, 2, 1, 1)
        self.basic_russian_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_russian_counter_2.setText("")
        self.basic_russian_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_russian_counter_2.setObjectName("basic_russian_counter_2")
        self.gridLayout_10.addWidget(self.basic_russian_counter_2, 1, 3, 1, 1)
        self.basic_english_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_english_max_2.setText("")
        self.basic_english_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_english_max_2.setObjectName("basic_english_max_2")
        self.gridLayout_10.addWidget(self.basic_english_max_2, 2, 1, 1, 1)
        self.basic_english_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_english_avg_2.setText("")
        self.basic_english_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_english_avg_2.setObjectName("basic_english_avg_2")
        self.gridLayout_10.addWidget(self.basic_english_avg_2, 2, 2, 1, 1)
        self.long_english_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_english_counter_2.setText("")
        self.long_english_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_english_counter_2.setObjectName("long_english_counter_2")
        self.gridLayout_10.addWidget(self.long_english_counter_2, 4, 3, 1, 1)
        self.basic_english_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_english_counter_2.setText("")
        self.basic_english_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_english_counter_2.setObjectName("basic_english_counter_2")
        self.gridLayout_10.addWidget(self.basic_english_counter_2, 2, 3, 1, 1)
        self.basic_english_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.basic_english_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.basic_english_name_2.setObjectName("basic_english_name_2")
        self.gridLayout_10.addWidget(self.basic_english_name_2, 2, 0, 1, 1)
        self.long_russian_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_russian_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_russian_name_2.setObjectName("long_russian_name_2")
        self.gridLayout_10.addWidget(self.long_russian_name_2, 3, 0, 1, 1)
        self.hard_russian_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.hard_russian_counter_2.setText("")
        self.hard_russian_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hard_russian_counter_2.setObjectName("hard_russian_counter_2")
        self.gridLayout_10.addWidget(self.hard_russian_counter_2, 5, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_9.setStyleSheet("font-size: 15px; font-weight: 600;border-bottom:1px solid black;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 0, 2, 1, 1)
        self.long_english_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_english_avg_2.setText("")
        self.long_english_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_english_avg_2.setObjectName("long_english_avg_2")
        self.gridLayout_10.addWidget(self.long_english_avg_2, 4, 2, 1, 1)
        self.hard_russian_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.hard_russian_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.hard_russian_name_2.setObjectName("hard_russian_name_2")
        self.gridLayout_10.addWidget(self.hard_russian_name_2, 5, 0, 1, 1)
        self.long_english_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_english_max_2.setText("")
        self.long_english_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_english_max_2.setObjectName("long_english_max_2")
        self.gridLayout_10.addWidget(self.long_english_max_2, 4, 1, 1, 1)
        self.long_english_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.long_english_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.long_english_name_2.setObjectName("long_english_name_2")
        self.gridLayout_10.addWidget(self.long_english_name_2, 4, 0, 1, 1)
        self.numbers_name_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.numbers_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.numbers_name_2.setObjectName("numbers_name_2")
        self.gridLayout_10.addWidget(self.numbers_name_2, 6, 0, 1, 1)
        self.numbers_max_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.numbers_max_2.setText("")
        self.numbers_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.numbers_max_2.setObjectName("numbers_max_2")
        self.gridLayout_10.addWidget(self.numbers_max_2, 6, 1, 1, 1)
        self.numbers_avg_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.numbers_avg_2.setText("")
        self.numbers_avg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.numbers_avg_2.setObjectName("numbers_avg_2")
        self.gridLayout_10.addWidget(self.numbers_avg_2, 6, 2, 1, 1)
        self.numbers_counter_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.numbers_counter_2.setText("")
        self.numbers_counter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.numbers_counter_2.setObjectName("numbers_counter_2")
        self.gridLayout_10.addWidget(self.numbers_counter_2, 6, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.gridWidget_2)
        self.tabWidget.addTab(self.profile, "")
        self.training = QtWidgets.QWidget()
        self.training.setObjectName("training")
        self.gridLayout = QtWidgets.QGridLayout(self.training)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.training)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 27, 0, 1, 1)
        self.tr_info_panel = QtWidgets.QLabel(self.training)
        self.tr_info_panel.setMinimumSize(QtCore.QSize(0, 50))
        self.tr_info_panel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tr_info_panel.setStyleSheet("font-size: 16px;\n"
"")
        self.tr_info_panel.setObjectName("tr_info_panel")
        self.gridLayout.addWidget(self.tr_info_panel, 20, 0, 1, 1)
        self.rez_empty_filler = QtWidgets.QLabel(self.training)
        self.rez_empty_filler.setText("")
        self.rez_empty_filler.setObjectName("rez_empty_filler")
        self.gridLayout.addWidget(self.rez_empty_filler, 26, 0, 1, 1)
        self.choose_long_english = QtWidgets.QPushButton(self.training)
        self.choose_long_english.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_long_english.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_long_english.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_long_english.setObjectName("choose_long_english")
        self.gridLayout.addWidget(self.choose_long_english, 4, 0, 1, 1)
        self.tr_text_field = QtWidgets.QLabel(self.training)
        self.tr_text_field.setMinimumSize(QtCore.QSize(800, 100))
        self.tr_text_field.setMaximumSize(QtCore.QSize(800, 150))
        self.tr_text_field.setStyleSheet("font-size: 15px;\n"
"")
        self.tr_text_field.setAlignment(QtCore.Qt.AlignCenter)
        self.tr_text_field.setWordWrap(True)
        self.tr_text_field.setObjectName("tr_text_field")
        self.gridLayout.addWidget(self.tr_text_field, 10, 0, 1, 1)
        self.choose_hard_russian = QtWidgets.QPushButton(self.training)
        self.choose_hard_russian.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_hard_russian.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_hard_russian.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_hard_russian.setObjectName("choose_hard_russian")
        self.gridLayout.addWidget(self.choose_hard_russian, 5, 0, 1, 1)
        self.rez_title = QtWidgets.QLabel(self.training)
        self.rez_title.setStyleSheet("text-align: center; font-size: 18px; font-weight: 600;")
        self.rez_title.setAlignment(QtCore.Qt.AlignCenter)
        self.rez_title.setObjectName("rez_title")
        self.gridLayout.addWidget(self.rez_title, 12, 0, 1, 1)
        self.rez_new_game = QtWidgets.QPushButton(self.training)
        self.rez_new_game.setMinimumSize(QtCore.QSize(50, 30))
        self.rez_new_game.setMaximumSize(QtCore.QSize(800, 30))
        self.rez_new_game.setObjectName("rez_new_game")
        self.gridLayout.addWidget(self.rez_new_game, 16, 0, 1, 1)
        self.choose_long_russian = QtWidgets.QPushButton(self.training)
        self.choose_long_russian.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_long_russian.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_long_russian.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_long_russian.setObjectName("choose_long_russian")
        self.gridLayout.addWidget(self.choose_long_russian, 3, 0, 1, 1)
        self.tr_come_back = QtWidgets.QPushButton(self.training)
        self.tr_come_back.setMinimumSize(QtCore.QSize(0, 40))
        self.tr_come_back.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tr_come_back.setObjectName("tr_come_back")
        self.gridLayout.addWidget(self.tr_come_back, 23, 0, 1, 1)
        self.tr_english_layout = QtWidgets.QWidget(self.training)
        self.tr_english_layout.setMinimumSize(QtCore.QSize(791, 281))
        self.tr_english_layout.setMaximumSize(QtCore.QSize(791, 281))
        self.tr_english_layout.setObjectName("tr_english_layout")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tr_english_layout)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.e_apostrophe = QtWidgets.QPushButton(self.tr_english_layout)
        self.e_apostrophe.setMinimumSize(QtCore.QSize(48, 48))
        self.e_apostrophe.setMaximumSize(QtCore.QSize(48, 48))
        self.e_apostrophe.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.e_apostrophe.setObjectName("e_apostrophe")
        self.horizontalLayout_7.addWidget(self.e_apostrophe)
        self.a_one = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_one.setMinimumSize(QtCore.QSize(48, 48))
        self.a_one.setMaximumSize(QtCore.QSize(48, 48))
        self.a_one.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_one.setObjectName("a_one")
        self.horizontalLayout_7.addWidget(self.a_one)
        self.a_two = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_two.setMinimumSize(QtCore.QSize(48, 48))
        self.a_two.setMaximumSize(QtCore.QSize(48, 48))
        self.a_two.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_two.setObjectName("a_two")
        self.horizontalLayout_7.addWidget(self.a_two)
        self.a_three = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_three.setMinimumSize(QtCore.QSize(48, 48))
        self.a_three.setMaximumSize(QtCore.QSize(48, 48))
        self.a_three.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_three.setObjectName("a_three")
        self.horizontalLayout_7.addWidget(self.a_three)
        self.a_four = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_four.setMinimumSize(QtCore.QSize(48, 48))
        self.a_four.setMaximumSize(QtCore.QSize(48, 48))
        self.a_four.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_four.setObjectName("a_four")
        self.horizontalLayout_7.addWidget(self.a_four)
        self.a_five = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_five.setMinimumSize(QtCore.QSize(48, 48))
        self.a_five.setMaximumSize(QtCore.QSize(48, 48))
        self.a_five.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_five.setObjectName("a_five")
        self.horizontalLayout_7.addWidget(self.a_five)
        self.a_six = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_six.setMinimumSize(QtCore.QSize(48, 48))
        self.a_six.setMaximumSize(QtCore.QSize(48, 48))
        self.a_six.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_six.setObjectName("a_six")
        self.horizontalLayout_7.addWidget(self.a_six)
        self.a_seven = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_seven.setMinimumSize(QtCore.QSize(48, 48))
        self.a_seven.setMaximumSize(QtCore.QSize(48, 48))
        self.a_seven.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_seven.setObjectName("a_seven")
        self.horizontalLayout_7.addWidget(self.a_seven)
        self.a_eight = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_eight.setMinimumSize(QtCore.QSize(48, 48))
        self.a_eight.setMaximumSize(QtCore.QSize(48, 48))
        self.a_eight.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_eight.setObjectName("a_eight")
        self.horizontalLayout_7.addWidget(self.a_eight)
        self.a_nine = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_nine.setMinimumSize(QtCore.QSize(48, 48))
        self.a_nine.setMaximumSize(QtCore.QSize(48, 48))
        self.a_nine.setStyleSheet("background: #64e1fd;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"border-radius: 7px;")
        self.a_nine.setObjectName("a_nine")
        self.horizontalLayout_7.addWidget(self.a_nine)
        self.a_zero = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_zero.setMinimumSize(QtCore.QSize(48, 48))
        self.a_zero.setMaximumSize(QtCore.QSize(48, 48))
        self.a_zero.setStyleSheet("border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"background: #77e0a8;\n"
"")
        self.a_zero.setObjectName("a_zero")
        self.horizontalLayout_7.addWidget(self.a_zero)
        self.a_def = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_def.setMinimumSize(QtCore.QSize(48, 48))
        self.a_def.setMaximumSize(QtCore.QSize(48, 48))
        self.a_def.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_def.setObjectName("a_def")
        self.horizontalLayout_7.addWidget(self.a_def)
        self.a_def_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_def_2.setMinimumSize(QtCore.QSize(48, 48))
        self.a_def_2.setMaximumSize(QtCore.QSize(48, 48))
        self.a_def_2.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"")
        self.a_def_2.setObjectName("a_def_2")
        self.horizontalLayout_7.addWidget(self.a_def_2)
        self.a_backspace = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_backspace.setMinimumSize(QtCore.QSize(0, 48))
        self.a_backspace.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_backspace.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"")
        self.a_backspace.setObjectName("a_backspace")
        self.horizontalLayout_7.addWidget(self.a_backspace)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.a_tab = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_tab.setMinimumSize(QtCore.QSize(0, 48))
        self.a_tab.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_tab.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"")
        self.a_tab.setObjectName("a_tab")
        self.horizontalLayout_8.addWidget(self.a_tab)
        self.a_q = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_q.setMinimumSize(QtCore.QSize(48, 48))
        self.a_q.setMaximumSize(QtCore.QSize(48, 48))
        self.a_q.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;")
        self.a_q.setObjectName("a_q")
        self.horizontalLayout_8.addWidget(self.a_q)
        self.a_w = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_w.setMinimumSize(QtCore.QSize(48, 48))
        self.a_w.setMaximumSize(QtCore.QSize(48, 48))
        self.a_w.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #64e1fd;\n"
"border-radius: 7px;")
        self.a_w.setObjectName("a_w")
        self.horizontalLayout_8.addWidget(self.a_w)
        self.a_e = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_e.setMinimumSize(QtCore.QSize(48, 48))
        self.a_e.setMaximumSize(QtCore.QSize(48, 48))
        self.a_e.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_e.setObjectName("a_e")
        self.horizontalLayout_8.addWidget(self.a_e)
        self.a_r = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_r.setMinimumSize(QtCore.QSize(48, 48))
        self.a_r.setMaximumSize(QtCore.QSize(48, 48))
        self.a_r.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_r.setObjectName("a_r")
        self.horizontalLayout_8.addWidget(self.a_r)
        self.a_t = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_t.setMinimumSize(QtCore.QSize(48, 48))
        self.a_t.setMaximumSize(QtCore.QSize(48, 48))
        self.a_t.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_t.setObjectName("a_t")
        self.horizontalLayout_8.addWidget(self.a_t)
        self.a_y = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_y.setMinimumSize(QtCore.QSize(48, 48))
        self.a_y.setMaximumSize(QtCore.QSize(48, 48))
        self.a_y.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_y.setObjectName("a_y")
        self.horizontalLayout_8.addWidget(self.a_y)
        self.a_u = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_u.setMinimumSize(QtCore.QSize(48, 48))
        self.a_u.setMaximumSize(QtCore.QSize(48, 48))
        self.a_u.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_u.setObjectName("a_u")
        self.horizontalLayout_8.addWidget(self.a_u)
        self.a_i = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_i.setMinimumSize(QtCore.QSize(48, 48))
        self.a_i.setMaximumSize(QtCore.QSize(48, 48))
        self.a_i.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_i.setObjectName("a_i")
        self.horizontalLayout_8.addWidget(self.a_i)
        self.a_o = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_o.setMinimumSize(QtCore.QSize(48, 48))
        self.a_o.setMaximumSize(QtCore.QSize(48, 48))
        self.a_o.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_o.setObjectName("a_o")
        self.horizontalLayout_8.addWidget(self.a_o)
        self.a_p = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_p.setMinimumSize(QtCore.QSize(48, 48))
        self.a_p.setMaximumSize(QtCore.QSize(48, 48))
        self.a_p.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_p.setObjectName("a_p")
        self.horizontalLayout_8.addWidget(self.a_p)
        self.a_sqr = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_sqr.setMinimumSize(QtCore.QSize(48, 48))
        self.a_sqr.setMaximumSize(QtCore.QSize(48, 48))
        self.a_sqr.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_sqr.setObjectName("a_sqr")
        self.horizontalLayout_8.addWidget(self.a_sqr)
        self.a_agsq = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_agsq.setMinimumSize(QtCore.QSize(48, 48))
        self.a_agsq.setMaximumSize(QtCore.QSize(48, 48))
        self.a_agsq.setStyleSheet("\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"")
        self.a_agsq.setObjectName("a_agsq")
        self.horizontalLayout_8.addWidget(self.a_agsq)
        self.a_backslesh = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_backslesh.setMinimumSize(QtCore.QSize(48, 48))
        self.a_backslesh.setMaximumSize(QtCore.QSize(48, 48))
        self.a_backslesh.setStyleSheet("\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;")
        self.a_backslesh.setObjectName("a_backslesh")
        self.horizontalLayout_8.addWidget(self.a_backslesh)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.a_caps = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_caps.setMinimumSize(QtCore.QSize(0, 48))
        self.a_caps.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_caps.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"")
        self.a_caps.setObjectName("a_caps")
        self.horizontalLayout_9.addWidget(self.a_caps)
        self.a_a = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_a.setMinimumSize(QtCore.QSize(48, 48))
        self.a_a.setMaximumSize(QtCore.QSize(48, 48))
        self.a_a.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;")
        self.a_a.setObjectName("a_a")
        self.horizontalLayout_9.addWidget(self.a_a)
        self.a_s = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_s.setMinimumSize(QtCore.QSize(48, 48))
        self.a_s.setMaximumSize(QtCore.QSize(48, 48))
        self.a_s.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #64e1fd;\n"
"border-radius: 7px;")
        self.a_s.setObjectName("a_s")
        self.horizontalLayout_9.addWidget(self.a_s)
        self.a_d = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_d.setMinimumSize(QtCore.QSize(48, 48))
        self.a_d.setMaximumSize(QtCore.QSize(48, 48))
        self.a_d.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #f79dc3;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"")
        self.a_d.setObjectName("a_d")
        self.horizontalLayout_9.addWidget(self.a_d)
        self.a_f = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_f.setMinimumSize(QtCore.QSize(48, 48))
        self.a_f.setMaximumSize(QtCore.QSize(48, 48))
        self.a_f.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_f.setObjectName("a_f")
        self.horizontalLayout_9.addWidget(self.a_f)
        self.a_g = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_g.setMinimumSize(QtCore.QSize(48, 48))
        self.a_g.setMaximumSize(QtCore.QSize(48, 48))
        self.a_g.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_g.setObjectName("a_g")
        self.horizontalLayout_9.addWidget(self.a_g)
        self.a_h = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_h.setMinimumSize(QtCore.QSize(48, 48))
        self.a_h.setMaximumSize(QtCore.QSize(48, 48))
        self.a_h.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_h.setObjectName("a_h")
        self.horizontalLayout_9.addWidget(self.a_h)
        self.a_j = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_j.setMinimumSize(QtCore.QSize(48, 48))
        self.a_j.setMaximumSize(QtCore.QSize(48, 48))
        self.a_j.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_j.setObjectName("a_j")
        self.horizontalLayout_9.addWidget(self.a_j)
        self.a_k = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_k.setMinimumSize(QtCore.QSize(48, 48))
        self.a_k.setMaximumSize(QtCore.QSize(48, 48))
        self.a_k.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_k.setObjectName("a_k")
        self.horizontalLayout_9.addWidget(self.a_k)
        self.a_l = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_l.setMinimumSize(QtCore.QSize(48, 48))
        self.a_l.setMaximumSize(QtCore.QSize(48, 48))
        self.a_l.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_l.setObjectName("a_l")
        self.horizontalLayout_9.addWidget(self.a_l)
        self.a_doubledot = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_doubledot.setMinimumSize(QtCore.QSize(48, 48))
        self.a_doubledot.setMaximumSize(QtCore.QSize(48, 48))
        self.a_doubledot.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_doubledot.setObjectName("a_doubledot")
        self.horizontalLayout_9.addWidget(self.a_doubledot)
        self.a_oneap = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_oneap.setMinimumSize(QtCore.QSize(48, 48))
        self.a_oneap.setMaximumSize(QtCore.QSize(48, 48))
        self.a_oneap.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_oneap.setObjectName("a_oneap")
        self.horizontalLayout_9.addWidget(self.a_oneap)
        self.a_enter = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_enter.setMinimumSize(QtCore.QSize(0, 48))
        self.a_enter.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_enter.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_enter.setObjectName("a_enter")
        self.horizontalLayout_9.addWidget(self.a_enter)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.a_shift = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_shift.setMinimumSize(QtCore.QSize(0, 48))
        self.a_shift.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_shift.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_shift.setObjectName("a_shift")
        self.horizontalLayout_10.addWidget(self.a_shift)
        self.a_z = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_z.setMinimumSize(QtCore.QSize(48, 48))
        self.a_z.setMaximumSize(QtCore.QSize(48, 48))
        self.a_z.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_z.setObjectName("a_z")
        self.horizontalLayout_10.addWidget(self.a_z)
        self.a_x = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_x.setMinimumSize(QtCore.QSize(48, 48))
        self.a_x.setMaximumSize(QtCore.QSize(48, 48))
        self.a_x.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_x.setObjectName("a_x")
        self.horizontalLayout_10.addWidget(self.a_x)
        self.a_c = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_c.setMinimumSize(QtCore.QSize(48, 48))
        self.a_c.setMaximumSize(QtCore.QSize(48, 48))
        self.a_c.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_c.setObjectName("a_c")
        self.horizontalLayout_10.addWidget(self.a_c)
        self.a_v = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_v.setMinimumSize(QtCore.QSize(48, 48))
        self.a_v.setMaximumSize(QtCore.QSize(48, 48))
        self.a_v.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_v.setObjectName("a_v")
        self.horizontalLayout_10.addWidget(self.a_v)
        self.a_b = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_b.setMinimumSize(QtCore.QSize(48, 48))
        self.a_b.setMaximumSize(QtCore.QSize(48, 48))
        self.a_b.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.a_b.setObjectName("a_b")
        self.horizontalLayout_10.addWidget(self.a_b)
        self.a_n = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_n.setMinimumSize(QtCore.QSize(48, 48))
        self.a_n.setMaximumSize(QtCore.QSize(48, 48))
        self.a_n.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.a_n.setObjectName("a_n")
        self.horizontalLayout_10.addWidget(self.a_n)
        self.a_m = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_m.setMinimumSize(QtCore.QSize(48, 48))
        self.a_m.setMaximumSize(QtCore.QSize(48, 48))
        self.a_m.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"\n"
"")
        self.a_m.setObjectName("a_m")
        self.horizontalLayout_10.addWidget(self.a_m)
        self.a_comma = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_comma.setMinimumSize(QtCore.QSize(48, 48))
        self.a_comma.setMaximumSize(QtCore.QSize(48, 48))
        self.a_comma.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"\n"
"")
        self.a_comma.setObjectName("a_comma")
        self.horizontalLayout_10.addWidget(self.a_comma)
        self.a_dot = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_dot.setMinimumSize(QtCore.QSize(48, 48))
        self.a_dot.setMaximumSize(QtCore.QSize(48, 48))
        self.a_dot.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_dot.setObjectName("a_dot")
        self.horizontalLayout_10.addWidget(self.a_dot)
        self.a_slesh = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_slesh.setMinimumSize(QtCore.QSize(48, 48))
        self.a_slesh.setMaximumSize(QtCore.QSize(48, 48))
        self.a_slesh.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"\n"
"")
        self.a_slesh.setObjectName("a_slesh")
        self.horizontalLayout_10.addWidget(self.a_slesh)
        self.a_shift_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_shift_2.setMinimumSize(QtCore.QSize(0, 48))
        self.a_shift_2.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_shift_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.a_shift_2.setObjectName("a_shift_2")
        self.horizontalLayout_10.addWidget(self.a_shift_2)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.r_lctrl_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_lctrl_2.setMinimumSize(QtCore.QSize(64, 48))
        self.r_lctrl_2.setMaximumSize(QtCore.QSize(64, 48))
        self.r_lctrl_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_lctrl_2.setObjectName("r_lctrl_2")
        self.horizontalLayout_11.addWidget(self.r_lctrl_2)
        self.r_fn_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_fn_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_fn_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_fn_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_fn_2.setObjectName("r_fn_2")
        self.horizontalLayout_11.addWidget(self.r_fn_2)
        self.r_lwin_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_lwin_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_lwin_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_lwin_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_lwin_2.setObjectName("r_lwin_2")
        self.horizontalLayout_11.addWidget(self.r_lwin_2)
        self.r_lalt_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_lalt_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_lalt_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_lalt_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_lalt_2.setObjectName("r_lalt_2")
        self.horizontalLayout_11.addWidget(self.r_lalt_2)
        self.a_space = QtWidgets.QPushButton(self.tr_english_layout)
        self.a_space.setMinimumSize(QtCore.QSize(0, 48))
        self.a_space.setMaximumSize(QtCore.QSize(16777215, 48))
        self.a_space.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;")
        self.a_space.setText("")
        self.a_space.setObjectName("a_space")
        self.horizontalLayout_11.addWidget(self.a_space)
        self.r_ralt_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_ralt_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ralt_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ralt_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_ralt_2.setObjectName("r_ralt_2")
        self.horizontalLayout_11.addWidget(self.r_ralt_2)
        self.r_rwin_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_rwin_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_rwin_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_rwin_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_rwin_2.setObjectName("r_rwin_2")
        self.horizontalLayout_11.addWidget(self.r_rwin_2)
        self.r_rctrl_2 = QtWidgets.QPushButton(self.tr_english_layout)
        self.r_rctrl_2.setMinimumSize(QtCore.QSize(64, 48))
        self.r_rctrl_2.setMaximumSize(QtCore.QSize(128, 48))
        self.r_rctrl_2.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_rctrl_2.setObjectName("r_rctrl_2")
        self.horizontalLayout_11.addWidget(self.r_rctrl_2)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_11)
        self.gridLayout.addWidget(self.tr_english_layout, 22, 0, 1, 1)
        self.tr_back_label = QtWidgets.QLabel(self.training)
        self.tr_back_label.setMinimumSize(QtCore.QSize(0, 10))
        self.tr_back_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tr_back_label.setText("")
        self.tr_back_label.setObjectName("tr_back_label")
        self.gridLayout.addWidget(self.tr_back_label, 31, 0, 1, 1)
        self.choose_basic_english = QtWidgets.QPushButton(self.training)
        self.choose_basic_english.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_basic_english.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_basic_english.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_basic_english.setObjectName("choose_basic_english")
        self.gridLayout.addWidget(self.choose_basic_english, 2, 0, 1, 1)
        self.tr_title = QtWidgets.QLabel(self.training)
        self.tr_title.setMinimumSize(QtCore.QSize(0, 20))
        self.tr_title.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tr_title.setStyleSheet("text-align: center; font-size: 18px; font-weight: 600;")
        self.tr_title.setAlignment(QtCore.Qt.AlignCenter)
        self.tr_title.setObjectName("tr_title")
        self.gridLayout.addWidget(self.tr_title, 8, 0, 1, 1)
        self.tr_first_letter = QtWidgets.QLabel(self.training)
        self.tr_first_letter.setMinimumSize(QtCore.QSize(0, 15))
        self.tr_first_letter.setMaximumSize(QtCore.QSize(16777215, 15))
        self.tr_first_letter.setAlignment(QtCore.Qt.AlignCenter)
        self.tr_first_letter.setObjectName("tr_first_letter")
        self.gridLayout.addWidget(self.tr_first_letter, 9, 0, 1, 1)
        self.rez_main_text = QtWidgets.QLabel(self.training)
        self.rez_main_text.setMaximumSize(QtCore.QSize(16777215, 400))
        self.rez_main_text.setText("")
        self.rez_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.rez_main_text.setWordWrap(True)
        self.rez_main_text.setObjectName("rez_main_text")
        self.gridLayout.addWidget(self.rez_main_text, 15, 0, 1, 1)
        self.choose_numbers = QtWidgets.QPushButton(self.training)
        self.choose_numbers.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_numbers.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_numbers.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_numbers.setObjectName("choose_numbers")
        self.gridLayout.addWidget(self.choose_numbers, 6, 0, 1, 1)
        self.rez_mistakes = QtWidgets.QLabel(self.training)
        self.rez_mistakes.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rez_mistakes.setStyleSheet("font-size: 16px;\n"
"")
        self.rez_mistakes.setObjectName("rez_mistakes")
        self.gridLayout.addWidget(self.rez_mistakes, 13, 0, 1, 1)
        self.choose_title = QtWidgets.QLabel(self.training)
        self.choose_title.setMinimumSize(QtCore.QSize(0, 100))
        self.choose_title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.choose_title.setStyleSheet("font-size: 24px; \n"
"font-weight: 600;")
        self.choose_title.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_title.setObjectName("choose_title")
        self.gridLayout.addWidget(self.choose_title, 0, 0, 1, 1)
        self.tr_russian_layout = QtWidgets.QWidget(self.training)
        self.tr_russian_layout.setMinimumSize(QtCore.QSize(791, 281))
        self.tr_russian_layout.setMaximumSize(QtCore.QSize(791, 281))
        self.tr_russian_layout.setObjectName("tr_russian_layout")
        self.formLayout = QtWidgets.QFormLayout(self.tr_russian_layout)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.r_apostrophe = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_apostrophe.setMinimumSize(QtCore.QSize(48, 48))
        self.r_apostrophe.setMaximumSize(QtCore.QSize(48, 48))
        self.r_apostrophe.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_apostrophe.setObjectName("r_apostrophe")
        self.horizontalLayout_2.addWidget(self.r_apostrophe)
        self.r_one = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_one.setMinimumSize(QtCore.QSize(48, 48))
        self.r_one.setMaximumSize(QtCore.QSize(48, 48))
        self.r_one.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_one.setObjectName("r_one")
        self.horizontalLayout_2.addWidget(self.r_one)
        self.r_two = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_two.setMinimumSize(QtCore.QSize(48, 48))
        self.r_two.setMaximumSize(QtCore.QSize(48, 48))
        self.r_two.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_two.setObjectName("r_two")
        self.horizontalLayout_2.addWidget(self.r_two)
        self.r_three = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_three.setMinimumSize(QtCore.QSize(48, 48))
        self.r_three.setMaximumSize(QtCore.QSize(48, 48))
        self.r_three.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_three.setObjectName("r_three")
        self.horizontalLayout_2.addWidget(self.r_three)
        self.r_four = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_four.setMinimumSize(QtCore.QSize(48, 48))
        self.r_four.setMaximumSize(QtCore.QSize(48, 48))
        self.r_four.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_four.setObjectName("r_four")
        self.horizontalLayout_2.addWidget(self.r_four)
        self.f_five = QtWidgets.QPushButton(self.tr_russian_layout)
        self.f_five.setMinimumSize(QtCore.QSize(48, 48))
        self.f_five.setMaximumSize(QtCore.QSize(48, 48))
        self.f_five.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.f_five.setObjectName("f_five")
        self.horizontalLayout_2.addWidget(self.f_five)
        self.r_six = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_six.setMinimumSize(QtCore.QSize(48, 48))
        self.r_six.setMaximumSize(QtCore.QSize(48, 48))
        self.r_six.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_six.setObjectName("r_six")
        self.horizontalLayout_2.addWidget(self.r_six)
        self.r_seven = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_seven.setMinimumSize(QtCore.QSize(48, 48))
        self.r_seven.setMaximumSize(QtCore.QSize(48, 48))
        self.r_seven.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_seven.setObjectName("r_seven")
        self.horizontalLayout_2.addWidget(self.r_seven)
        self.r_eight = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_eight.setMinimumSize(QtCore.QSize(48, 48))
        self.r_eight.setMaximumSize(QtCore.QSize(48, 48))
        self.r_eight.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_eight.setObjectName("r_eight")
        self.horizontalLayout_2.addWidget(self.r_eight)
        self.r_nine = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_nine.setMinimumSize(QtCore.QSize(48, 48))
        self.r_nine.setMaximumSize(QtCore.QSize(48, 48))
        self.r_nine.setStyleSheet("background: #64e1fd;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"border-radius: 7px;")
        self.r_nine.setObjectName("r_nine")
        self.horizontalLayout_2.addWidget(self.r_nine)
        self.r_zero = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_zero.setMinimumSize(QtCore.QSize(48, 48))
        self.r_zero.setMaximumSize(QtCore.QSize(48, 48))
        self.r_zero.setStyleSheet("border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"background: #77e0a8;\n"
"")
        self.r_zero.setObjectName("r_zero")
        self.horizontalLayout_2.addWidget(self.r_zero)
        self.r_def = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_def.setMinimumSize(QtCore.QSize(48, 48))
        self.r_def.setMaximumSize(QtCore.QSize(48, 48))
        self.r_def.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_def.setObjectName("r_def")
        self.horizontalLayout_2.addWidget(self.r_def)
        self.r_eq = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_eq.setMinimumSize(QtCore.QSize(48, 48))
        self.r_eq.setMaximumSize(QtCore.QSize(48, 48))
        self.r_eq.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"")
        self.r_eq.setObjectName("r_eq")
        self.horizontalLayout_2.addWidget(self.r_eq)
        self.r_backspace = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_backspace.setMinimumSize(QtCore.QSize(0, 48))
        self.r_backspace.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_backspace.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"")
        self.r_backspace.setObjectName("r_backspace")
        self.horizontalLayout_2.addWidget(self.r_backspace)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.r_tab = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_tab.setMinimumSize(QtCore.QSize(0, 48))
        self.r_tab.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_tab.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"")
        self.r_tab.setObjectName("r_tab")
        self.horizontalLayout_3.addWidget(self.r_tab)
        self.r_yi = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_yi.setMinimumSize(QtCore.QSize(48, 48))
        self.r_yi.setMaximumSize(QtCore.QSize(48, 48))
        self.r_yi.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;")
        self.r_yi.setObjectName("r_yi")
        self.horizontalLayout_3.addWidget(self.r_yi)
        self.r_ce = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_ce.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ce.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ce.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #64e1fd;\n"
"border-radius: 7px;")
        self.r_ce.setObjectName("r_ce")
        self.horizontalLayout_3.addWidget(self.r_ce)
        self.r_u = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_u.setMinimumSize(QtCore.QSize(48, 48))
        self.r_u.setMaximumSize(QtCore.QSize(48, 48))
        self.r_u.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_u.setObjectName("r_u")
        self.horizontalLayout_3.addWidget(self.r_u)
        self.r_k = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_k.setMinimumSize(QtCore.QSize(48, 48))
        self.r_k.setMaximumSize(QtCore.QSize(48, 48))
        self.r_k.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_k.setObjectName("r_k")
        self.horizontalLayout_3.addWidget(self.r_k)
        self.r_e = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_e.setMinimumSize(QtCore.QSize(48, 48))
        self.r_e.setMaximumSize(QtCore.QSize(48, 48))
        self.r_e.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_e.setObjectName("r_e")
        self.horizontalLayout_3.addWidget(self.r_e)
        self.r_n = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_n.setMinimumSize(QtCore.QSize(48, 48))
        self.r_n.setMaximumSize(QtCore.QSize(48, 48))
        self.r_n.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_n.setObjectName("r_n")
        self.horizontalLayout_3.addWidget(self.r_n)
        self.r_g = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_g.setMinimumSize(QtCore.QSize(48, 48))
        self.r_g.setMaximumSize(QtCore.QSize(48, 48))
        self.r_g.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_g.setObjectName("r_g")
        self.horizontalLayout_3.addWidget(self.r_g)
        self.r_sh = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_sh.setMinimumSize(QtCore.QSize(48, 48))
        self.r_sh.setMaximumSize(QtCore.QSize(48, 48))
        self.r_sh.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_sh.setObjectName("r_sh")
        self.horizontalLayout_3.addWidget(self.r_sh)
        self.r_che_2 = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_che_2.setMinimumSize(QtCore.QSize(48, 48))
        self.r_che_2.setMaximumSize(QtCore.QSize(48, 48))
        self.r_che_2.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_che_2.setObjectName("r_che_2")
        self.horizontalLayout_3.addWidget(self.r_che_2)
        self.r_z = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_z.setMinimumSize(QtCore.QSize(48, 48))
        self.r_z.setMaximumSize(QtCore.QSize(48, 48))
        self.r_z.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_z.setObjectName("r_z")
        self.horizontalLayout_3.addWidget(self.r_z)
        self.r_h = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_h.setMinimumSize(QtCore.QSize(48, 48))
        self.r_h.setMaximumSize(QtCore.QSize(48, 48))
        self.r_h.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_h.setObjectName("r_h")
        self.horizontalLayout_3.addWidget(self.r_h)
        self.r_solid = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_solid.setMinimumSize(QtCore.QSize(48, 48))
        self.r_solid.setMaximumSize(QtCore.QSize(48, 48))
        self.r_solid.setStyleSheet("\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"")
        self.r_solid.setObjectName("r_solid")
        self.horizontalLayout_3.addWidget(self.r_solid)
        self.r_backslesh = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_backslesh.setMinimumSize(QtCore.QSize(48, 48))
        self.r_backslesh.setMaximumSize(QtCore.QSize(48, 48))
        self.r_backslesh.setStyleSheet("\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;")
        self.r_backslesh.setObjectName("r_backslesh")
        self.horizontalLayout_3.addWidget(self.r_backslesh)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.r_caps = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_caps.setMinimumSize(QtCore.QSize(0, 48))
        self.r_caps.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_caps.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"")
        self.r_caps.setObjectName("r_caps")
        self.horizontalLayout_4.addWidget(self.r_caps)
        self.r_f = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_f.setMinimumSize(QtCore.QSize(48, 48))
        self.r_f.setMaximumSize(QtCore.QSize(48, 48))
        self.r_f.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;")
        self.r_f.setObjectName("r_f")
        self.horizontalLayout_4.addWidget(self.r_f)
        self.r_ui = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_ui.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ui.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ui.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #64e1fd;\n"
"border-radius: 7px;")
        self.r_ui.setObjectName("r_ui")
        self.horizontalLayout_4.addWidget(self.r_ui)
        self.r_v = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_v.setMinimumSize(QtCore.QSize(48, 48))
        self.r_v.setMaximumSize(QtCore.QSize(48, 48))
        self.r_v.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"background: #f79dc3;\n"
"border-radius: 7px;\n"
"\n"
"\n"
"")
        self.r_v.setObjectName("r_v")
        self.horizontalLayout_4.addWidget(self.r_v)
        self.r_a = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_a.setMinimumSize(QtCore.QSize(48, 48))
        self.r_a.setMaximumSize(QtCore.QSize(48, 48))
        self.r_a.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_a.setObjectName("r_a")
        self.horizontalLayout_4.addWidget(self.r_a)
        self.r_p = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_p.setMinimumSize(QtCore.QSize(48, 48))
        self.r_p.setMaximumSize(QtCore.QSize(48, 48))
        self.r_p.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_p.setObjectName("r_p")
        self.horizontalLayout_4.addWidget(self.r_p)
        self.r_r = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_r.setMinimumSize(QtCore.QSize(48, 48))
        self.r_r.setMaximumSize(QtCore.QSize(48, 48))
        self.r_r.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_r.setObjectName("r_r")
        self.horizontalLayout_4.addWidget(self.r_r)
        self.r_o = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_o.setMinimumSize(QtCore.QSize(48, 48))
        self.r_o.setMaximumSize(QtCore.QSize(48, 48))
        self.r_o.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_o.setObjectName("r_o")
        self.horizontalLayout_4.addWidget(self.r_o)
        self.r_l = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_l.setMinimumSize(QtCore.QSize(48, 48))
        self.r_l.setMaximumSize(QtCore.QSize(48, 48))
        self.r_l.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_l.setObjectName("r_l")
        self.horizontalLayout_4.addWidget(self.r_l)
        self.r_de = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_de.setMinimumSize(QtCore.QSize(48, 48))
        self.r_de.setMaximumSize(QtCore.QSize(48, 48))
        self.r_de.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_de.setObjectName("r_de")
        self.horizontalLayout_4.addWidget(self.r_de)
        self.r_ze = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_ze.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ze.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ze.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_ze.setObjectName("r_ze")
        self.horizontalLayout_4.addWidget(self.r_ze)
        self.r_eo = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_eo.setMinimumSize(QtCore.QSize(48, 48))
        self.r_eo.setMaximumSize(QtCore.QSize(48, 48))
        self.r_eo.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_eo.setObjectName("r_eo")
        self.horizontalLayout_4.addWidget(self.r_eo)
        self.r_enter = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_enter.setMinimumSize(QtCore.QSize(0, 48))
        self.r_enter.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_enter.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_enter.setObjectName("r_enter")
        self.horizontalLayout_4.addWidget(self.r_enter)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.r_lshift = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_lshift.setMinimumSize(QtCore.QSize(0, 48))
        self.r_lshift.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_lshift.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_lshift.setObjectName("r_lshift")
        self.horizontalLayout_5.addWidget(self.r_lshift)
        self.r_ya = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_ya.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ya.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ya.setStyleSheet("border-radius: 7px;\n"
"background: #77e0a8;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_ya.setObjectName("r_ya")
        self.horizontalLayout_5.addWidget(self.r_ya)
        self.r_che = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_che.setMinimumSize(QtCore.QSize(48, 48))
        self.r_che.setMaximumSize(QtCore.QSize(48, 48))
        self.r_che.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_che.setObjectName("r_che")
        self.horizontalLayout_5.addWidget(self.r_che)
        self.r_s = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_s.setMinimumSize(QtCore.QSize(48, 48))
        self.r_s.setMaximumSize(QtCore.QSize(48, 48))
        self.r_s.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_s.setObjectName("r_s")
        self.horizontalLayout_5.addWidget(self.r_s)
        self.r_m = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_m.setMinimumSize(QtCore.QSize(48, 48))
        self.r_m.setMaximumSize(QtCore.QSize(48, 48))
        self.r_m.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_m.setObjectName("r_m")
        self.horizontalLayout_5.addWidget(self.r_m)
        self.r_i = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_i.setMinimumSize(QtCore.QSize(48, 48))
        self.r_i.setMaximumSize(QtCore.QSize(48, 48))
        self.r_i.setStyleSheet("background: #ffc07d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_i.setObjectName("r_i")
        self.horizontalLayout_5.addWidget(self.r_i)
        self.r_t = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_t.setMinimumSize(QtCore.QSize(48, 48))
        self.r_t.setMaximumSize(QtCore.QSize(48, 48))
        self.r_t.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_t.setObjectName("r_t")
        self.horizontalLayout_5.addWidget(self.r_t)
        self.r_soft = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_soft.setMinimumSize(QtCore.QSize(48, 48))
        self.r_soft.setMaximumSize(QtCore.QSize(48, 48))
        self.r_soft.setStyleSheet("background: #fcef7d;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"\n"
"")
        self.r_soft.setObjectName("r_soft")
        self.horizontalLayout_5.addWidget(self.r_soft)
        self.r_b = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_b.setMinimumSize(QtCore.QSize(48, 48))
        self.r_b.setMaximumSize(QtCore.QSize(48, 48))
        self.r_b.setStyleSheet("background: #f79dc3;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"\n"
"")
        self.r_b.setObjectName("r_b")
        self.horizontalLayout_5.addWidget(self.r_b)
        self.r_yu = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_yu.setMinimumSize(QtCore.QSize(48, 48))
        self.r_yu.setMaximumSize(QtCore.QSize(48, 48))
        self.r_yu.setStyleSheet("background: #64e1fd;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_yu.setObjectName("r_yu")
        self.horizontalLayout_5.addWidget(self.r_yu)
        self.r_dot = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_dot.setMinimumSize(QtCore.QSize(48, 48))
        self.r_dot.setMaximumSize(QtCore.QSize(48, 48))
        self.r_dot.setStyleSheet("font-weight: 500;\n"
"font-size: 15px;\n"
"border-radius: 7px;\n"
"background: #77e0a8;\n"
"\n"
"")
        self.r_dot.setObjectName("r_dot")
        self.horizontalLayout_5.addWidget(self.r_dot)
        self.r_rshift = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_rshift.setMinimumSize(QtCore.QSize(0, 48))
        self.r_rshift.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_rshift.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_rshift.setObjectName("r_rshift")
        self.horizontalLayout_5.addWidget(self.r_rshift)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.r_lctrl = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_lctrl.setMinimumSize(QtCore.QSize(64, 48))
        self.r_lctrl.setMaximumSize(QtCore.QSize(64, 48))
        self.r_lctrl.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"\n"
"")
        self.r_lctrl.setObjectName("r_lctrl")
        self.horizontalLayout_6.addWidget(self.r_lctrl)
        self.r_fn = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_fn.setMinimumSize(QtCore.QSize(48, 48))
        self.r_fn.setMaximumSize(QtCore.QSize(48, 48))
        self.r_fn.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_fn.setObjectName("r_fn")
        self.horizontalLayout_6.addWidget(self.r_fn)
        self.r_lwin = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_lwin.setMinimumSize(QtCore.QSize(48, 48))
        self.r_lwin.setMaximumSize(QtCore.QSize(48, 48))
        self.r_lwin.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_lwin.setObjectName("r_lwin")
        self.horizontalLayout_6.addWidget(self.r_lwin)
        self.r_lalt = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_lalt.setMinimumSize(QtCore.QSize(48, 48))
        self.r_lalt.setMaximumSize(QtCore.QSize(48, 48))
        self.r_lalt.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_lalt.setObjectName("r_lalt")
        self.horizontalLayout_6.addWidget(self.r_lalt)
        self.r_space = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_space.setMinimumSize(QtCore.QSize(0, 48))
        self.r_space.setMaximumSize(QtCore.QSize(16777215, 48))
        self.r_space.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;")
        self.r_space.setText("")
        self.r_space.setObjectName("r_space")
        self.horizontalLayout_6.addWidget(self.r_space)
        self.r_ralt = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_ralt.setMinimumSize(QtCore.QSize(48, 48))
        self.r_ralt.setMaximumSize(QtCore.QSize(48, 48))
        self.r_ralt.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"\n"
"")
        self.r_ralt.setObjectName("r_ralt")
        self.horizontalLayout_6.addWidget(self.r_ralt)
        self.r_rwin = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_rwin.setMinimumSize(QtCore.QSize(48, 48))
        self.r_rwin.setMaximumSize(QtCore.QSize(48, 48))
        self.r_rwin.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;\n"
"font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_rwin.setObjectName("r_rwin")
        self.horizontalLayout_6.addWidget(self.r_rwin)
        self.r_rctrl = QtWidgets.QPushButton(self.tr_russian_layout)
        self.r_rctrl.setMinimumSize(QtCore.QSize(64, 48))
        self.r_rctrl.setMaximumSize(QtCore.QSize(128, 48))
        self.r_rctrl.setStyleSheet("background: #9cd3fa;\n"
"border-radius: 7px;font-weight: 500;\n"
"font-size: 15px;\n"
"")
        self.r_rctrl.setObjectName("r_rctrl")
        self.horizontalLayout_6.addWidget(self.r_rctrl)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.gridLayout.addWidget(self.tr_russian_layout, 21, 0, 1, 1)
        self.choose_basic_russian = QtWidgets.QPushButton(self.training)
        self.choose_basic_russian.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_basic_russian.setMaximumSize(QtCore.QSize(900, 40))
        self.choose_basic_russian.setStyleSheet("font-size: 17px;\n"
"")
        self.choose_basic_russian.setObjectName("choose_basic_russian")
        self.gridLayout.addWidget(self.choose_basic_russian, 1, 0, 1, 1)
        self.tr_writing_area = QtWidgets.QLineEdit(self.training)
        self.tr_writing_area.setMinimumSize(QtCore.QSize(800, 30))
        self.tr_writing_area.setMaximumSize(QtCore.QSize(800, 30))
        self.tr_writing_area.setObjectName("tr_writing_area")
        self.gridLayout.addWidget(self.tr_writing_area, 11, 0, 1, 1)
        self.tabWidget.addTab(self.training, "")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.info)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setStyleSheet("font-size: 19px; font-weight: 600;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.info)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.info)
        self.label_5.setMaximumSize(QtCore.QSize(800, 130))
        self.label_5.setStyleSheet("font-size: 18px;")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.info)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("font-size: 23px; font-weight: 700;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.info)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 205))
        self.label_6.setStyleSheet("font-size: 18px;\n"
"")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.image = QtWidgets.QLabel(self.info)
        self.image.setMaximumSize(QtCore.QSize(900, 320))
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 4, 0, 1, 1)
        self.tabWidget.addTab(self.info, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_18.setText(_translate("MainWindow", "Количество"))
        self.label_19.setText(_translate("MainWindow", "Название"))
        self.basic_russia_name_2.setText(_translate("MainWindow", "Стандартный русский"))
        self.label_2.setText(_translate("MainWindow", "Максимум"))
        self.basic_english_name_2.setText(_translate("MainWindow", "Стандартный английский"))
        self.long_russian_name_2.setText(_translate("MainWindow", "Длинный русский"))
        self.label_9.setText(_translate("MainWindow", "Среднее"))
        self.hard_russian_name_2.setText(_translate("MainWindow", "Сложный русский"))
        self.long_english_name_2.setText(_translate("MainWindow", "Длинный английский"))
        self.numbers_name_2.setText(_translate("MainWindow", "Числа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile), _translate("MainWindow", "Профиль"))
        self.tr_info_panel.setText(_translate("MainWindow", "                                                         Ошибки: 0                                                     Скорость: 0"))
        self.choose_long_english.setText(_translate("MainWindow", "Длинный английский"))
        self.tr_text_field.setText(_translate("MainWindow", "I was a birch tree, white slenderness in the middle of a meadow, but had no name for what I was. My leaves drank of the sunlight that streamed through them and set their green aglow, my leaves danced in the wind, which made a harp of my branches, but I did not see or hear. Waning days turned me brittle golden, frost stripped me bare, snow blew about me during my long drowse, then Orion hunted his quarry beyond this heaven and the sun swung north to blaze me awake, but none of this did I sense. And yet I marked it all, for I lived. Each cell within me felt in a secret way how the sky first shone aloud and afterward grew quiet, air gusted or whooped or lay dreaming, rain flung chill and laughter, water and worms did their work for my reaching roots, nestlings piped where I sheltered them and soughed."))
        self.choose_hard_russian.setText(_translate("MainWindow", "Сложный русский"))
        self.rez_title.setText(_translate("MainWindow", "Ваш результат:"))
        self.rez_new_game.setText(_translate("MainWindow", "Новая игра"))
        self.choose_long_russian.setText(_translate("MainWindow", "Длинный русский"))
        self.tr_come_back.setText(_translate("MainWindow", "Вренуться к панели выбора"))
        self.e_apostrophe.setText(_translate("MainWindow", "`"))
        self.a_one.setText(_translate("MainWindow", "1"))
        self.a_two.setText(_translate("MainWindow", "2"))
        self.a_three.setText(_translate("MainWindow", "3"))
        self.a_four.setText(_translate("MainWindow", "4"))
        self.a_five.setText(_translate("MainWindow", "5"))
        self.a_six.setText(_translate("MainWindow", "6"))
        self.a_seven.setText(_translate("MainWindow", "7"))
        self.a_eight.setText(_translate("MainWindow", "8"))
        self.a_nine.setText(_translate("MainWindow", "9"))
        self.a_zero.setText(_translate("MainWindow", "0"))
        self.a_def.setText(_translate("MainWindow", "-"))
        self.a_def_2.setText(_translate("MainWindow", "="))
        self.a_backspace.setText(_translate("MainWindow", "Back"))
        self.a_tab.setText(_translate("MainWindow", "Tab"))
        self.a_q.setText(_translate("MainWindow", "Q"))
        self.a_w.setText(_translate("MainWindow", "W"))
        self.a_e.setText(_translate("MainWindow", "E"))
        self.a_r.setText(_translate("MainWindow", "R"))
        self.a_t.setText(_translate("MainWindow", "T"))
        self.a_y.setText(_translate("MainWindow", "Y"))
        self.a_u.setText(_translate("MainWindow", "U"))
        self.a_i.setText(_translate("MainWindow", "I"))
        self.a_o.setText(_translate("MainWindow", "O"))
        self.a_p.setText(_translate("MainWindow", "P"))
        self.a_sqr.setText(_translate("MainWindow", "["))
        self.a_agsq.setText(_translate("MainWindow", "]"))
        self.a_backslesh.setText(_translate("MainWindow", "\\"))
        self.a_caps.setText(_translate("MainWindow", "Caps"))
        self.a_a.setText(_translate("MainWindow", "A"))
        self.a_s.setText(_translate("MainWindow", "S"))
        self.a_d.setText(_translate("MainWindow", "D"))
        self.a_f.setText(_translate("MainWindow", "F"))
        self.a_g.setText(_translate("MainWindow", "G"))
        self.a_h.setText(_translate("MainWindow", "H"))
        self.a_j.setText(_translate("MainWindow", "J"))
        self.a_k.setText(_translate("MainWindow", "K"))
        self.a_l.setText(_translate("MainWindow", "L"))
        self.a_doubledot.setText(_translate("MainWindow", ";"))
        self.a_oneap.setText(_translate("MainWindow", "\'"))
        self.a_enter.setText(_translate("MainWindow", "Enter"))
        self.a_shift.setText(_translate("MainWindow", "Shift"))
        self.a_z.setText(_translate("MainWindow", "Z"))
        self.a_x.setText(_translate("MainWindow", "X"))
        self.a_c.setText(_translate("MainWindow", "C"))
        self.a_v.setText(_translate("MainWindow", "V"))
        self.a_b.setText(_translate("MainWindow", "B"))
        self.a_n.setText(_translate("MainWindow", "N"))
        self.a_m.setText(_translate("MainWindow", "M"))
        self.a_comma.setText(_translate("MainWindow", ","))
        self.a_dot.setText(_translate("MainWindow", "."))
        self.a_slesh.setText(_translate("MainWindow", "/"))
        self.a_shift_2.setText(_translate("MainWindow", "Shift"))
        self.r_lctrl_2.setText(_translate("MainWindow", "Ctrl"))
        self.r_fn_2.setText(_translate("MainWindow", "Fn"))
        self.r_lwin_2.setText(_translate("MainWindow", "Win"))
        self.r_lalt_2.setText(_translate("MainWindow", "Alt"))
        self.r_ralt_2.setText(_translate("MainWindow", "Alt"))
        self.r_rwin_2.setText(_translate("MainWindow", "Win"))
        self.r_rctrl_2.setText(_translate("MainWindow", "Ctrl"))
        self.choose_basic_english.setText(_translate("MainWindow", "Стандартный английский"))
        self.tr_title.setText(_translate("MainWindow", "Стандартный русский"))
        self.tr_first_letter.setText(_translate("MainWindow", "Игра начнется как только вы введете первую букву"))
        self.choose_numbers.setText(_translate("MainWindow", "Числа"))
        self.rez_mistakes.setText(_translate("MainWindow", "                                                         Ошибки: 0                                                     Скорость: 0"))
        self.choose_title.setText(_translate("MainWindow", "Выберете режим"))
        self.r_apostrophe.setText(_translate("MainWindow", "`"))
        self.r_one.setText(_translate("MainWindow", "1"))
        self.r_two.setText(_translate("MainWindow", "2"))
        self.r_three.setText(_translate("MainWindow", "3"))
        self.r_four.setText(_translate("MainWindow", "4"))
        self.f_five.setText(_translate("MainWindow", "5"))
        self.r_six.setText(_translate("MainWindow", "6"))
        self.r_seven.setText(_translate("MainWindow", "7"))
        self.r_eight.setText(_translate("MainWindow", "8"))
        self.r_nine.setText(_translate("MainWindow", "9"))
        self.r_zero.setText(_translate("MainWindow", "0"))
        self.r_def.setText(_translate("MainWindow", "-"))
        self.r_eq.setText(_translate("MainWindow", "="))
        self.r_backspace.setText(_translate("MainWindow", "Back"))
        self.r_tab.setText(_translate("MainWindow", "Tab"))
        self.r_yi.setText(_translate("MainWindow", "Й"))
        self.r_ce.setText(_translate("MainWindow", "Ц"))
        self.r_u.setText(_translate("MainWindow", "У"))
        self.r_k.setText(_translate("MainWindow", "К"))
        self.r_e.setText(_translate("MainWindow", "Е"))
        self.r_n.setText(_translate("MainWindow", "Н"))
        self.r_g.setText(_translate("MainWindow", "Г"))
        self.r_sh.setText(_translate("MainWindow", "Ш"))
        self.r_che_2.setText(_translate("MainWindow", "Щ"))
        self.r_z.setText(_translate("MainWindow", "З"))
        self.r_h.setText(_translate("MainWindow", "Х"))
        self.r_solid.setText(_translate("MainWindow", "Ъ"))
        self.r_backslesh.setText(_translate("MainWindow", "\\"))
        self.r_caps.setText(_translate("MainWindow", "Caps"))
        self.r_f.setText(_translate("MainWindow", "Ф"))
        self.r_ui.setText(_translate("MainWindow", "Ы"))
        self.r_v.setText(_translate("MainWindow", "В"))
        self.r_a.setText(_translate("MainWindow", "А"))
        self.r_p.setText(_translate("MainWindow", "П"))
        self.r_r.setText(_translate("MainWindow", "Р"))
        self.r_o.setText(_translate("MainWindow", "О"))
        self.r_l.setText(_translate("MainWindow", "Л"))
        self.r_de.setText(_translate("MainWindow", "Д"))
        self.r_ze.setText(_translate("MainWindow", "Ж"))
        self.r_eo.setText(_translate("MainWindow", "Э"))
        self.r_enter.setText(_translate("MainWindow", "Enter"))
        self.r_lshift.setText(_translate("MainWindow", "Shift"))
        self.r_ya.setText(_translate("MainWindow", "Я"))
        self.r_che.setText(_translate("MainWindow", "Ч"))
        self.r_s.setText(_translate("MainWindow", "С"))
        self.r_m.setText(_translate("MainWindow", "М"))
        self.r_i.setText(_translate("MainWindow", "И"))
        self.r_t.setText(_translate("MainWindow", "Т"))
        self.r_soft.setText(_translate("MainWindow", "Ь"))
        self.r_b.setText(_translate("MainWindow", "Б"))
        self.r_yu.setText(_translate("MainWindow", "Ю"))
        self.r_dot.setText(_translate("MainWindow", "."))
        self.r_rshift.setText(_translate("MainWindow", "Shift"))
        self.r_lctrl.setText(_translate("MainWindow", "Ctrl"))
        self.r_fn.setText(_translate("MainWindow", "Fn"))
        self.r_lwin.setText(_translate("MainWindow", "Win"))
        self.r_lalt.setText(_translate("MainWindow", "Alt"))
        self.r_ralt.setText(_translate("MainWindow", "Alt"))
        self.r_rwin.setText(_translate("MainWindow", "Win"))
        self.r_rctrl.setText(_translate("MainWindow", "Ctrl"))
        self.choose_basic_russian.setText(_translate("MainWindow", "Стандартный русский"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.training), _translate("MainWindow", "Тренировки"))
        self.label_7.setText(_translate("MainWindow", "Правильное положение пальцев"))
        self.label_5.setText(_translate("MainWindow", "    В настоящее время все большее количество людей осваивают компьютеры. А что является одним из главных средств связи между человеком и компьютером? Конечно же клавиатура. И без правильного и быстрого коммуницирования с ней можно потерять много времени. Именно для уменьшения времени печати и было создано это приложение. Оно учит человека слепой печати методом десяти пальцев на различных раскладках клавиатуры. "))
        self.label.setText(_translate("MainWindow", "Узнай как печатать быстро"))
        self.label_6.setText(_translate("MainWindow", "Пожалуйста во время обучения соблюдайте следующие рекомендации:\n"
"    1. Сохраняйте пальцы на правильных позициях постоянно\n"
"    2. Правильно сядьте перед компьютером\n"
"    3. Ни за что не подглядывайте на клавиатуру\n"
"    4. Не стремитесь сразу печатать очень быстро\n"
"    5. Начните ускоряться, как почувствуете, что пальцы нажимаю на правильные кнопки\n"
"    6. Старайтесь стремиться к правильности а не к скорости\n"
"    7. Всегда просматривайте текст на одно-два слова вперед\n"
"    8. Если чувствуешь, что твоя эффективность понижается, остановись\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("MainWindow", "Информация о приложении"))
